Data workfloww in which I built an end-to-end ETL pipeline in AWS and performed data visualisation/analytics on Tableau, and Machine Learning on SageMaker Studio. Please view my Tableau dashboards at: https://public.tableau.com/app/profile/huynh.ngoc.tram.nguyen/viz/Frauddataset/Transactionoverviewdashboard

==== About Dataset
. Dataset properties
* 6362621 records
* csv format
* File size ~ 500MB
. Field descriptions
* *step* - maps a unit of time in the real world. In this case 1 step is 1 hour of time. Total steps 744 (30 days simulation).
* *type* - CASH-IN, CASH-OUT, DEBIT, PAYMENT and TRANSFER.
* *amount* - amount of the transaction in local currency.
* *nameOrig* - customer who started the transaction
* *oldbalanceOrg* - initial balance before the transaction
* *newbalanceOrig* - new balance after the transaction
* *nameDest* - customer who is the recipient of the transaction
* *oldbalanceDest* - initial balance recipient before the transaction. Note that there is not information for customers that start with M (Merchants).
* *newbalanceDest* - new balance recipient after the transaction. Note that there is no information for customers that start with M (Merchants).
* *isFraud* - These are the transactions made by the fraudulent agents inside the simulation. In this specific dataset the fraudulent behavior of the agents aims to profit by taking control of customers' accounts and try to empty the funds by transferring to another account and then cashing out of the system.
* *isFlaggedFraud* - The business model aims to control massive transfers from one account to another and flags illegal attempts. An illegal attempt in this dataset is an attempt to transfer more than 200,000 in a single transaction.
